### ISSUE TITLE
World parsing (the big dilemma)

### ISSUE THREAD

**Issue by The-Noah** [BZFlagCommunity/webbzw#3]
This is currently the **big dilemma**, which is how the world parsing engine should work. I see three options:

1. **Rewrite it from scratch in TypeScript.**
2. Rip BZFlag's out and get it to run on WebAssembly.
3. Rewrite BZFlag's from scratch in C++ and make it compatible with WebAssembly, and make fairly easy to "drop in" to BZFlag as a replacement.

As far as I'm concerned ripping out BZFlag's and rewriting it would be almost the same difficulty (at least for me). The third option would be quite interesting but would also be a lot of work. Your thoughts are welcome!

**Comment by The-Noah** [comment]
I'm leaning towards writing it from scratch in TypeScript.

**Comment by allejo** [comment]
I'd personally lean towards writing a new implementation; there's no way I'd trust BZFlag code outside of BZFlag 😅

The parsing itself _shouldn't_ be too difficult? There's a lot to write and it'll be tedious, but there's no logic to parse. It's just objects to read and transform in respective TS objects.

For inspiration, JeffM has written a parser in his LibBZFlag project, https://github.com/JeffM2501/LibBZFlag/tree/master/BZFlag.IO.BZW

**Comment by The-Noah** [comment]
Just got an idea on how it can be made a lot better 😄

Thanks for the link, that'll be extremely useful!
